<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(

    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(

        ),
    )
);