<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(

    ),

    'service_manager' => array(

    ),

    'router' => array(
// Uncomment below to add routes
//        'routes' => array(
//            '{MODULE_SLUG}' => array(
//                'type' => 'Literal',
//                'options' => array(
//                    'route' => '/{MODULE_SLUG}',
//                    'defaults' => array(
//                        '__NAMESPACE__' => '{MODULE_NAME}\Controller',
//                        'controller' => '{MODULE_NAME}',
//                        'action' => 'index',
//                    )
//                ),
//                'may_terminate' => true,
//                'child_routes' => array(
//                    'default' => array(
//                        'type' => 'Segment',
//                        'options' => array(
//                            'route' => '/[:controller[/:action]]',
//                            'constraints' => array(
//                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                            )
//                        )
//                    )
//                )
//            )
//        )
    )
);
